package com.examseating.model; // Package declaration: Defines the package this class belongs to (com.examseating.model)

import javax.persistence.*; // Import statement: Imports all JPA annotations for database mapping
import javax.validation.constraints.*; // Import statement: Imports all validation constraints
import java.time.LocalDateTime; // Import statement: Imports LocalDateTime class for timestamp fields
import java.time.LocalDate; // Import statement: Imports LocalDate class for date fields
import java.time.LocalTime; // Import statement: Imports LocalTime class for time fields

/**
 * Exam entity representing an examination
 */
@Entity // JPA annotation: Marks this class as a database entity (table mapping)
@Table(name = "exams") // JPA annotation: Specifies the database table name as 'exams'
public class Exam { // Class declaration: Public class named Exam representing an exam entity
    
    @Id // JPA annotation: Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // JPA annotation: Specifies auto-increment strategy for primary key generation
    private Long id; // Field declaration: Primary key field (auto-generated by database)
    
    @NotBlank(message = "Exam ID is required") // Validation annotation: Ensures field is not blank
    @Column(unique = true, nullable = false) // JPA annotation: Makes column unique and not nullable
    private String examId; // Field declaration: Unique exam identifier string
    
    @NotBlank(message = "Subject is required") // Validation annotation: Ensures field is not blank
    @Size(max = 100, message = "Subject must not exceed 100 characters") // Validation annotation: Limits string length to 100 characters
    private String subject; // Field declaration: Exam subject name
    
    @NotNull(message = "Exam date is required") // Validation annotation: Ensures field is not null
    private LocalDate examDate; // Field declaration: Date when the exam is scheduled
    
    @NotNull(message = "Start time is required") // Validation annotation: Ensures field is not null
    private LocalTime startTime; // Field declaration: Time when the exam starts
    
    @NotNull(message = "End time is required") // Validation annotation: Ensures field is not null
    private LocalTime endTime; // Field declaration: Time when the exam ends
    
    @Min(value = 30, message = "Duration must be at least 30 minutes") // Validation annotation: Ensures minimum value of 30
    @Max(value = 480, message = "Duration cannot exceed 8 hours") // Validation annotation: Ensures maximum value of 480
    private Integer durationMinutes; // Field declaration: Duration of the exam in minutes
    
    @Size(max = 500, message = "Instructions must not exceed 500 characters") // Validation annotation: Limits string length to 500 characters
    private String instructions; // Field declaration: Special instructions for the exam
    
    @NotBlank(message = "Academic year is required") // Validation annotation: Ensures field is not blank
    private String academicYear; // Field declaration: Academic year (e.g., 2024-2025)
    
    @NotBlank(message = "Semester is required") // Validation annotation: Ensures field is not blank
    private String semester; // Field declaration: Semester (e.g., Fall, Spring)
    
    @Enumerated(EnumType.STRING) // JPA annotation: Stores enum as string in database instead of ordinal
    private ExamType examType = ExamType.REGULAR; // Field declaration: Type of exam (REGULAR, MAKEUP, FINAL, MIDTERM, QUIZ) with default REGULAR
    
    @Enumerated(EnumType.STRING) // JPA annotation: Stores enum as string in database instead of ordinal
    private ExamStatus status = ExamStatus.SCHEDULED; // Field declaration: Exam status (SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED) with default SCHEDULED
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private Boolean isActive = true; // Field declaration: Soft delete flag (true = active, false = deleted)
    
    @Column(nullable = false, updatable = false) // JPA annotation: Makes column not nullable and not updatable
    private LocalDateTime createdAt; // Field declaration: Timestamp when exam record was created
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private LocalDateTime updatedAt; // Field declaration: Timestamp when exam record was last updated
    
    // Enums
    public enum ExamType { // Enum declaration: Defines the types of exams available
        REGULAR, MAKEUP, FINAL, MIDTERM, QUIZ // Enum constants: Different exam types
    }
    
    public enum ExamStatus { // Enum declaration: Defines the possible statuses of an exam
        SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED // Enum constants: Different exam statuses
    }
    
    // Constructors
    public Exam() { // Constructor declaration: No-argument constructor (default)
        this.createdAt = LocalDateTime.now(); // Assignment: Sets createdAt to current timestamp
        this.updatedAt = LocalDateTime.now(); // Assignment: Sets updatedAt to current timestamp
    }
    
    public Exam(String examId, String subject, LocalDate examDate, LocalTime startTime, LocalTime endTime) { // Constructor declaration: Parameterized constructor with basic exam info
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.examId = examId; // Assignment: Sets examId field
        this.subject = subject; // Assignment: Sets subject field
        this.examDate = examDate; // Assignment: Sets examDate field
        this.startTime = startTime; // Assignment: Sets startTime field
        this.endTime = endTime; // Assignment: Sets endTime field
    }
    
    // Getters and Setters
    public Long getId() { // Getter method: Returns the id field value
        return id; // Return statement: Returns the primary key id
    }
    
    public void setId(Long id) { // Setter method: Sets the id field value
        this.id = id; // Assignment: Sets the primary key id
    }
    
    public String getExamId() { // Getter method: Returns the examId field value
        return examId; // Return statement: Returns the exam ID string
    }
    
    public void setExamId(String examId) { // Setter method: Sets the examId field value
        this.examId = examId; // Assignment: Sets the exam ID
    }
    
    public String getSubject() { // Getter method: Returns the subject field value
        return subject; // Return statement: Returns the exam subject
    }
    
    public void setSubject(String subject) { // Setter method: Sets the subject field value
        this.subject = subject; // Assignment: Sets the exam subject
    }
    
    public LocalDate getExamDate() { // Getter method: Returns the examDate field value
        return examDate; // Return statement: Returns the exam date
    }
    
    public void setExamDate(LocalDate examDate) { // Setter method: Sets the examDate field value
        this.examDate = examDate; // Assignment: Sets the exam date
    }
    
    public LocalTime getStartTime() { // Getter method: Returns the startTime field value
        return startTime; // Return statement: Returns the exam start time
    }
    
    public void setStartTime(LocalTime startTime) { // Setter method: Sets the startTime field value
        this.startTime = startTime; // Assignment: Sets the exam start time
    }
    
    public LocalTime getEndTime() { // Getter method: Returns the endTime field value
        return endTime; // Return statement: Returns the exam end time
    }
    
    public void setEndTime(LocalTime endTime) { // Setter method: Sets the endTime field value
        this.endTime = endTime; // Assignment: Sets the exam end time
    }
    
    public Integer getDurationMinutes() { // Getter method: Returns the durationMinutes field value
        return durationMinutes; // Return statement: Returns the exam duration in minutes
    }
    
    public void setDurationMinutes(Integer durationMinutes) { // Setter method: Sets the durationMinutes field value
        this.durationMinutes = durationMinutes; // Assignment: Sets the exam duration
    }
    
    public String getInstructions() { // Getter method: Returns the instructions field value
        return instructions; // Return statement: Returns the exam instructions
    }
    
    public void setInstructions(String instructions) { // Setter method: Sets the instructions field value
        this.instructions = instructions; // Assignment: Sets the exam instructions
    }
    
    public String getAcademicYear() { // Getter method: Returns the academicYear field value
        return academicYear; // Return statement: Returns the academic year
    }
    
    public void setAcademicYear(String academicYear) { // Setter method: Sets the academicYear field value
        this.academicYear = academicYear; // Assignment: Sets the academic year
    }
    
    public String getSemester() { // Getter method: Returns the semester field value
        return semester; // Return statement: Returns the semester
    }
    
    public void setSemester(String semester) { // Setter method: Sets the semester field value
        this.semester = semester; // Assignment: Sets the semester
    }
    
    public ExamType getExamType() { // Getter method: Returns the examType field value
        return examType; // Return statement: Returns the exam type enum
    }
    
    public void setExamType(ExamType examType) { // Setter method: Sets the examType field value
        this.examType = examType; // Assignment: Sets the exam type
    }
    
    public ExamStatus getStatus() { // Getter method: Returns the status field value
        return status; // Return statement: Returns the exam status enum
    }
    
    public void setStatus(ExamStatus status) { // Setter method: Sets the status field value
        this.status = status; // Assignment: Sets the exam status
    }
    
    public Boolean getIsActive() { // Getter method: Returns the isActive field value
        return isActive; // Return statement: Returns the active status flag
    }
    
    public void setIsActive(Boolean isActive) { // Setter method: Sets the isActive field value
        this.isActive = isActive; // Assignment: Sets the active status flag
    }
    
    public LocalDateTime getCreatedAt() { // Getter method: Returns the createdAt field value
        return createdAt; // Return statement: Returns the creation timestamp
    }
    
    public void setCreatedAt(LocalDateTime createdAt) { // Setter method: Sets the createdAt field value
        this.createdAt = createdAt; // Assignment: Sets the creation timestamp
    }
    
    public LocalDateTime getUpdatedAt() { // Getter method: Returns the updatedAt field value
        return updatedAt; // Return statement: Returns the last update timestamp
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) { // Setter method: Sets the updatedAt field value
        this.updatedAt = updatedAt; // Assignment: Sets the last update timestamp
    }
    
    @PreUpdate // JPA annotation: Marks this method to run before entity update operation
    public void preUpdate() { // Method declaration: Lifecycle callback method that runs before update
        this.updatedAt = LocalDateTime.now(); // Assignment: Updates the updatedAt timestamp to current time
    }
    
    @Override // Annotation: Indicates this method overrides the Object class toString() method
    public String toString() { // Method declaration: Overrides toString() to provide string representation of object
        return "Exam{" + // String concatenation: Starts building string representation
                "id=" + id + // String concatenation: Adds id field
                ", examId='" + examId + '\'' + // String concatenation: Adds examId field with quotes
                ", subject='" + subject + '\'' + // String concatenation: Adds subject field with quotes
                ", examDate=" + examDate + // String concatenation: Adds examDate field
                ", startTime=" + startTime + // String concatenation: Adds startTime field
                ", endTime=" + endTime + // String concatenation: Adds endTime field
                ", durationMinutes=" + durationMinutes + // String concatenation: Adds durationMinutes field
                ", instructions='" + instructions + '\'' + // String concatenation: Adds instructions field with quotes
                ", academicYear='" + academicYear + '\'' + // String concatenation: Adds academicYear field with quotes
                ", semester='" + semester + '\'' + // String concatenation: Adds semester field with quotes
                ", examType=" + examType + // String concatenation: Adds examType enum
                ", status=" + status + // String concatenation: Adds status enum
                ", isActive=" + isActive + // String concatenation: Adds isActive flag
                ", createdAt=" + createdAt + // String concatenation: Adds createdAt timestamp
                ", updatedAt=" + updatedAt + // String concatenation: Adds updatedAt timestamp
                '}'; // String concatenation: Closes the string representation
    }
} // Class closing brace: End of Exam class
