package com.examseating.model; // Package declaration: Defines the package this class belongs to (com.examseating.model)

import javax.persistence.*; // Import statement: Imports all JPA annotations for database mapping
import javax.validation.constraints.*; // Import statement: Imports all validation constraints
import java.time.LocalDateTime; // Import statement: Imports LocalDateTime class for timestamp fields
import java.util.List; // Import statement: Imports List interface for collections

/**
 * Room entity representing an examination room
 */
@Entity // JPA annotation: Marks this class as a database entity (table mapping)
@Table(name = "rooms") // JPA annotation: Specifies the database table name as 'rooms'
public class Room { // Class declaration: Public class named Room representing a room entity
    
    @Id // JPA annotation: Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // JPA annotation: Specifies auto-increment strategy for primary key generation
    private Long id; // Field declaration: Primary key field (auto-generated by database)
    
    @NotBlank(message = "Room ID is required") // Validation annotation: Ensures field is not blank
    @Column(unique = true, nullable = false) // JPA annotation: Makes column unique and not nullable
    private String roomId; // Field declaration: Unique room identifier string
    
    @NotBlank(message = "Room name is required") // Validation annotation: Ensures field is not blank
    @Size(max = 100, message = "Room name must not exceed 100 characters") // Validation annotation: Limits string length to 100 characters
    private String name; // Field declaration: Room name/description
    
    @Min(value = 1, message = "Capacity must be at least 1") // Validation annotation: Ensures minimum value of 1
    @Max(value = 1000, message = "Capacity cannot exceed 1000") // Validation annotation: Ensures maximum value of 1000
    private Integer capacity; // Field declaration: Maximum number of students the room can accommodate
    
    @Min(value = 1, message = "Rows must be at least 1") // Validation annotation: Ensures minimum value of 1
    private Integer rows; // Field declaration: Number of rows in the room layout
    
    @Min(value = 1, message = "Columns must be at least 1") // Validation annotation: Ensures minimum value of 1
    private Integer columns; // Field declaration: Number of columns in the room layout
    
    private String building; // Field declaration: Building name where the room is located
    
    private String floor; // Field declaration: Floor number where the room is located
    
    @ElementCollection // JPA annotation: Marks this field as a collection of basic types stored in separate table
    @CollectionTable(name = "room_facilities", joinColumns = @JoinColumn(name = "room_id")) // JPA annotation: Specifies join table name and foreign key column
    @Column(name = "facility") // JPA annotation: Specifies column name in the join table
    private List<String> facilities; // Field declaration: List of facilities available in the room (e.g., AC, Projector, Wheelchair Access)
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private Boolean isActive = true; // Field declaration: Soft delete flag (true = active, false = deleted)
    
    @Column(nullable = false, updatable = false) // JPA annotation: Makes column not nullable and not updatable
    private LocalDateTime createdAt; // Field declaration: Timestamp when room record was created
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private LocalDateTime updatedAt; // Field declaration: Timestamp when room record was last updated
    
    // Constructors
    public Room() { // Constructor declaration: No-argument constructor (default)
        this.createdAt = LocalDateTime.now(); // Assignment: Sets createdAt to current timestamp
        this.updatedAt = LocalDateTime.now(); // Assignment: Sets updatedAt to current timestamp
    }
    
    public Room(String roomId, String name, Integer capacity, Integer rows, Integer columns) { // Constructor declaration: Parameterized constructor with room details
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.roomId = roomId; // Assignment: Sets roomId field
        this.name = name; // Assignment: Sets name field
        this.capacity = capacity; // Assignment: Sets capacity field
        this.rows = rows; // Assignment: Sets rows field
        this.columns = columns; // Assignment: Sets columns field
    }
    
    // Getters and Setters
    public Long getId() { // Getter method: Returns the id field value
        return id; // Return statement: Returns the primary key id
    }
    
    public void setId(Long id) { // Setter method: Sets the id field value
        this.id = id; // Assignment: Sets the primary key id
    }
    
    public String getRoomId() { // Getter method: Returns the roomId field value
        return roomId; // Return statement: Returns the room ID string
    }
    
    public void setRoomId(String roomId) { // Setter method: Sets the roomId field value
        this.roomId = roomId; // Assignment: Sets the room ID
    }
    
    public String getName() { // Getter method: Returns the name field value
        return name; // Return statement: Returns the room name
    }
    
    public void setName(String name) { // Setter method: Sets the name field value
        this.name = name; // Assignment: Sets the room name
    }
    
    public Integer getCapacity() { // Getter method: Returns the capacity field value
        return capacity; // Return statement: Returns the room capacity
    }
    
    public void setCapacity(Integer capacity) { // Setter method: Sets the capacity field value
        this.capacity = capacity; // Assignment: Sets the room capacity
    }
    
    public Integer getRows() { // Getter method: Returns the rows field value
        return rows; // Return statement: Returns the number of rows
    }
    
    public void setRows(Integer rows) { // Setter method: Sets the rows field value
        this.rows = rows; // Assignment: Sets the number of rows
    }
    
    public Integer getColumns() { // Getter method: Returns the columns field value
        return columns; // Return statement: Returns the number of columns
    }
    
    public void setColumns(Integer columns) { // Setter method: Sets the columns field value
        this.columns = columns; // Assignment: Sets the number of columns
    }
    
    public String getBuilding() { // Getter method: Returns the building field value
        return building; // Return statement: Returns the building name
    }
    
    public void setBuilding(String building) { // Setter method: Sets the building field value
        this.building = building; // Assignment: Sets the building name
    }
    
    public String getFloor() { // Getter method: Returns the floor field value
        return floor; // Return statement: Returns the floor number
    }
    
    public void setFloor(String floor) { // Setter method: Sets the floor field value
        this.floor = floor; // Assignment: Sets the floor number
    }
    
    public List<String> getFacilities() { // Getter method: Returns the facilities field value
        return facilities; // Return statement: Returns the list of facilities
    }
    
    public void setFacilities(List<String> facilities) { // Setter method: Sets the facilities field value
        this.facilities = facilities; // Assignment: Sets the list of facilities
    }
    
    public Boolean getIsActive() { // Getter method: Returns the isActive field value
        return isActive; // Return statement: Returns the active status flag
    }
    
    public void setIsActive(Boolean isActive) { // Setter method: Sets the isActive field value
        this.isActive = isActive; // Assignment: Sets the active status flag
    }
    
    public LocalDateTime getCreatedAt() { // Getter method: Returns the createdAt field value
        return createdAt; // Return statement: Returns the creation timestamp
    }
    
    public void setCreatedAt(LocalDateTime createdAt) { // Setter method: Sets the createdAt field value
        this.createdAt = createdAt; // Assignment: Sets the creation timestamp
    }
    
    public LocalDateTime getUpdatedAt() { // Getter method: Returns the updatedAt field value
        return updatedAt; // Return statement: Returns the last update timestamp
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) { // Setter method: Sets the updatedAt field value
        this.updatedAt = updatedAt; // Assignment: Sets the last update timestamp
    }
    
    @PreUpdate // JPA annotation: Marks this method to run before entity update operation
    public void preUpdate() { // Method declaration: Lifecycle callback method that runs before update
        this.updatedAt = LocalDateTime.now(); // Assignment: Updates the updatedAt timestamp to current time
    }
    
    @Override // Annotation: Indicates this method overrides the Object class toString() method
    public String toString() { // Method declaration: Overrides toString() to provide string representation of object
        return "Room{" + // String concatenation: Starts building string representation
                "id=" + id + // String concatenation: Adds id field
                ", roomId='" + roomId + '\'' + // String concatenation: Adds roomId field with quotes
                ", name='" + name + '\'' + // String concatenation: Adds name field with quotes
                ", capacity=" + capacity + // String concatenation: Adds capacity field
                ", rows=" + rows + // String concatenation: Adds rows field
                ", columns=" + columns + // String concatenation: Adds columns field
                ", building='" + building + '\'' + // String concatenation: Adds building field with quotes
                ", floor='" + floor + '\'' + // String concatenation: Adds floor field with quotes
                ", facilities=" + facilities + // String concatenation: Adds facilities list
                ", isActive=" + isActive + // String concatenation: Adds isActive flag
                ", createdAt=" + createdAt + // String concatenation: Adds createdAt timestamp
                ", updatedAt=" + updatedAt + // String concatenation: Adds updatedAt timestamp
                '}'; // String concatenation: Closes the string representation
    }
} // Class closing brace: End of Room class
