package com.examseating.model; // Package declaration: Defines the package this class belongs to (com.examseating.model)

import javax.persistence.*; // Import statement: Imports all JPA annotations for database mapping
import javax.validation.constraints.*; // Import statement: Imports all validation constraints
import java.time.LocalDateTime; // Import statement: Imports LocalDateTime class for timestamp fields
import java.util.Date; // Import statement: Imports Date class for legacy date support
import java.util.List; // Import statement: Imports List interface for collections

/**
 * SeatingArrangement entity representing a complete seating arrangement for an exam
 */
@Entity // JPA annotation: Marks this class as a database entity (table mapping)
@Table(name = "seating_arrangements") // JPA annotation: Specifies the database table name as 'seating_arrangements'
public class SeatingArrangement { // Class declaration: Public class named SeatingArrangement representing a complete seating plan entity
    
    @Id // JPA annotation: Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // JPA annotation: Specifies auto-increment strategy for primary key generation
    private Long id; // Field declaration: Primary key field (auto-generated by database)
    
    @NotNull(message = "Exam ID is required") // Validation annotation: Ensures field is not null
    private Long examId; // Field declaration: Foreign key reference to the exam this arrangement is for
    
    @Min(value = 0, message = "Total students cannot be negative") // Validation annotation: Ensures minimum value of 0
    private Integer totalStudents; // Field declaration: Total number of students in this arrangement
    
    @Min(value = 0, message = "Total rooms cannot be negative") // Validation annotation: Ensures minimum value of 0
    private Integer totalRooms; // Field declaration: Total number of rooms used in this arrangement
    
    @Temporal(TemporalType.TIMESTAMP) // JPA annotation: Specifies temporal type as TIMESTAMP for Date field
    private Date generatedAt; // Field declaration: Timestamp when the seating arrangement was generated
    
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY) // JPA annotation: One-to-many relationship with cascade all and lazy loading
    @JoinColumn(name = "arrangement_id") // JPA annotation: Specifies foreign key column in child table
    private List<SeatingAssignment> assignments; // Field declaration: List of individual seat assignments for this arrangement
    
    @Column(nullable = false, updatable = false) // JPA annotation: Makes column not nullable and not updatable
    private LocalDateTime createdAt; // Field declaration: Timestamp when arrangement record was created
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private LocalDateTime updatedAt; // Field declaration: Timestamp when arrangement record was last updated
    
    // Constructors
    public SeatingArrangement() { // Constructor declaration: No-argument constructor (default)
        this.createdAt = LocalDateTime.now(); // Assignment: Sets createdAt to current timestamp
        this.updatedAt = LocalDateTime.now(); // Assignment: Sets updatedAt to current timestamp
        this.generatedAt = new Date(); // Assignment: Sets generatedAt to current date/time
    }
    
    public SeatingArrangement(Long examId, Integer totalStudents, Integer totalRooms) { // Constructor declaration: Parameterized constructor with arrangement details
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.examId = examId; // Assignment: Sets examId field
        this.totalStudents = totalStudents; // Assignment: Sets totalStudents field
        this.totalRooms = totalRooms; // Assignment: Sets totalRooms field
    }
    
    // Getters and Setters
    public Long getId() { // Getter method: Returns the id field value
        return id; // Return statement: Returns the primary key id
    }
    
    public void setId(Long id) { // Setter method: Sets the id field value
        this.id = id; // Assignment: Sets the primary key id
    }
    
    public Long getExamId() { // Getter method: Returns the examId field value
        return examId; // Return statement: Returns the exam ID
    }
    
    public void setExamId(Long examId) { // Setter method: Sets the examId field value
        this.examId = examId; // Assignment: Sets the exam ID
    }
    
    public Integer getTotalStudents() { // Getter method: Returns the totalStudents field value
        return totalStudents; // Return statement: Returns the total number of students
    }
    
    public void setTotalStudents(Integer totalStudents) { // Setter method: Sets the totalStudents field value
        this.totalStudents = totalStudents; // Assignment: Sets the total number of students
    }
    
    public Integer getTotalRooms() { // Getter method: Returns the totalRooms field value
        return totalRooms; // Return statement: Returns the total number of rooms
    }
    
    public void setTotalRooms(Integer totalRooms) { // Setter method: Sets the totalRooms field value
        this.totalRooms = totalRooms; // Assignment: Sets the total number of rooms
    }
    
    public Date getGeneratedAt() { // Getter method: Returns the generatedAt field value
        return generatedAt; // Return statement: Returns the generation timestamp
    }
    
    public void setGeneratedAt(Date generatedAt) { // Setter method: Sets the generatedAt field value
        this.generatedAt = generatedAt; // Assignment: Sets the generation timestamp
    }
    
    public List<SeatingAssignment> getAssignments() { // Getter method: Returns the assignments field value
        return assignments; // Return statement: Returns the list of seating assignments
    }
    
    public void setAssignments(List<SeatingAssignment> assignments) { // Setter method: Sets the assignments field value
        this.assignments = assignments; // Assignment: Sets the list of seating assignments
    }
    
    public LocalDateTime getCreatedAt() { // Getter method: Returns the createdAt field value
        return createdAt; // Return statement: Returns the creation timestamp
    }
    
    public void setCreatedAt(LocalDateTime createdAt) { // Setter method: Sets the createdAt field value
        this.createdAt = createdAt; // Assignment: Sets the creation timestamp
    }
    
    public LocalDateTime getUpdatedAt() { // Getter method: Returns the updatedAt field value
        return updatedAt; // Return statement: Returns the last update timestamp
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) { // Setter method: Sets the updatedAt field value
        this.updatedAt = updatedAt; // Assignment: Sets the last update timestamp
    }
    
    @PreUpdate // JPA annotation: Marks this method to run before entity update operation
    public void preUpdate() { // Method declaration: Lifecycle callback method that runs before update
        this.updatedAt = LocalDateTime.now(); // Assignment: Updates the updatedAt timestamp to current time
    }
    
    @Override // Annotation: Indicates this method overrides the Object class toString() method
    public String toString() { // Method declaration: Overrides toString() to provide string representation of object
        return "SeatingArrangement{" + // String concatenation: Starts building string representation
                "id=" + id + // String concatenation: Adds id field
                ", examId=" + examId + // String concatenation: Adds examId field
                ", totalStudents=" + totalStudents + // String concatenation: Adds totalStudents field
                ", totalRooms=" + totalRooms + // String concatenation: Adds totalRooms field
                ", generatedAt=" + generatedAt + // String concatenation: Adds generatedAt timestamp
                ", assignments=" + (assignments != null ? assignments.size() + " assignments" : "null") + // String concatenation: Adds assignments count or null
                ", createdAt=" + createdAt + // String concatenation: Adds createdAt timestamp
                ", updatedAt=" + updatedAt + // String concatenation: Adds updatedAt timestamp
                '}'; // String concatenation: Closes the string representation
    }
} // Class closing brace: End of SeatingArrangement class
