package com.examseating.model; // Package declaration: Defines the package this class belongs to (com.examseating.model)

import javax.persistence.*; // Import statement: Imports all JPA annotations for database mapping
import javax.validation.constraints.*; // Import statement: Imports all validation constraints
import java.time.LocalDateTime; // Import statement: Imports LocalDateTime class for timestamp fields

/**
 * SeatingAssignment entity representing a student's seat assignment
 */
@Entity // JPA annotation: Marks this class as a database entity (table mapping)
@Table(name = "seating_assignments") // JPA annotation: Specifies the database table name as 'seating_assignments'
public class SeatingAssignment { // Class declaration: Public class named SeatingAssignment representing a seat assignment entity
    
    @Id // JPA annotation: Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // JPA annotation: Specifies auto-increment strategy for primary key generation
    private Long id; // Field declaration: Primary key field (auto-generated by database)
    
    @NotBlank(message = "Student ID is required") // Validation annotation: Ensures field is not blank
    private String studentId; // Field declaration: Student ID who is assigned to this seat
    
    @NotBlank(message = "Room ID is required") // Validation annotation: Ensures field is not blank
    private String roomId; // Field declaration: Room ID where the student is assigned
    
    @Min(value = 1, message = "Seat number must be at least 1") // Validation annotation: Ensures minimum value of 1
    private Integer seatNumber; // Field declaration: Seat number within the room
    
    @Min(value = 1, message = "Row must be at least 1") // Validation annotation: Ensures minimum value of 1
    private Integer row; // Field declaration: Row number in the room layout
    
    @Min(value = 1, message = "Column must be at least 1") // Validation annotation: Ensures minimum value of 1
    private Integer column; // Field declaration: Column number in the room layout
    
    private String qrCode; // Field declaration: QR code string for seat verification
    
    @Column(nullable = false, updatable = false) // JPA annotation: Makes column not nullable and not updatable
    private LocalDateTime createdAt; // Field declaration: Timestamp when assignment was created
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private LocalDateTime updatedAt; // Field declaration: Timestamp when assignment was last updated
    
    // Constructors
    public SeatingAssignment() { // Constructor declaration: No-argument constructor (default)
        this.createdAt = LocalDateTime.now(); // Assignment: Sets createdAt to current timestamp
        this.updatedAt = LocalDateTime.now(); // Assignment: Sets updatedAt to current timestamp
    }
    
    public SeatingAssignment(String studentId, String roomId, Integer seatNumber, Integer row, Integer column) { // Constructor declaration: Parameterized constructor with assignment details
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.studentId = studentId; // Assignment: Sets studentId field
        this.roomId = roomId; // Assignment: Sets roomId field
        this.seatNumber = seatNumber; // Assignment: Sets seatNumber field
        this.row = row; // Assignment: Sets row field
        this.column = column; // Assignment: Sets column field
    }
    
    // Getters and Setters
    public Long getId() { // Getter method: Returns the id field value
        return id; // Return statement: Returns the primary key id
    }
    
    public void setId(Long id) { // Setter method: Sets the id field value
        this.id = id; // Assignment: Sets the primary key id
    }
    
    public String getStudentId() { // Getter method: Returns the studentId field value
        return studentId; // Return statement: Returns the student ID
    }
    
    public void setStudentId(String studentId) { // Setter method: Sets the studentId field value
        this.studentId = studentId; // Assignment: Sets the student ID
    }
    
    public String getRoomId() { // Getter method: Returns the roomId field value
        return roomId; // Return statement: Returns the room ID
    }
    
    public void setRoomId(String roomId) { // Setter method: Sets the roomId field value
        this.roomId = roomId; // Assignment: Sets the room ID
    }
    
    public Integer getSeatNumber() { // Getter method: Returns the seatNumber field value
        return seatNumber; // Return statement: Returns the seat number
    }
    
    public void setSeatNumber(Integer seatNumber) { // Setter method: Sets the seatNumber field value
        this.seatNumber = seatNumber; // Assignment: Sets the seat number
    }
    
    public Integer getRow() { // Getter method: Returns the row field value
        return row; // Return statement: Returns the row number
    }
    
    public void setRow(Integer row) { // Setter method: Sets the row field value
        this.row = row; // Assignment: Sets the row number
    }
    
    public Integer getColumn() { // Getter method: Returns the column field value
        return column; // Return statement: Returns the column number
    }
    
    public void setColumn(Integer column) { // Setter method: Sets the column field value
        this.column = column; // Assignment: Sets the column number
    }
    
    public String getQrCode() { // Getter method: Returns the qrCode field value
        return qrCode; // Return statement: Returns the QR code string
    }
    
    public void setQrCode(String qrCode) { // Setter method: Sets the qrCode field value
        this.qrCode = qrCode; // Assignment: Sets the QR code
    }
    
    public LocalDateTime getCreatedAt() { // Getter method: Returns the createdAt field value
        return createdAt; // Return statement: Returns the creation timestamp
    }
    
    public void setCreatedAt(LocalDateTime createdAt) { // Setter method: Sets the createdAt field value
        this.createdAt = createdAt; // Assignment: Sets the creation timestamp
    }
    
    public LocalDateTime getUpdatedAt() { // Getter method: Returns the updatedAt field value
        return updatedAt; // Return statement: Returns the last update timestamp
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) { // Setter method: Sets the updatedAt field value
        this.updatedAt = updatedAt; // Assignment: Sets the last update timestamp
    }
    
    @PreUpdate // JPA annotation: Marks this method to run before entity update operation
    public void preUpdate() { // Method declaration: Lifecycle callback method that runs before update
        this.updatedAt = LocalDateTime.now(); // Assignment: Updates the updatedAt timestamp to current time
    }
    
    @Override // Annotation: Indicates this method overrides the Object class toString() method
    public String toString() { // Method declaration: Overrides toString() to provide string representation of object
        return "SeatingAssignment{" + // String concatenation: Starts building string representation
                "id=" + id + // String concatenation: Adds id field
                ", studentId='" + studentId + '\'' + // String concatenation: Adds studentId field with quotes
                ", roomId='" + roomId + '\'' + // String concatenation: Adds roomId field with quotes
                ", seatNumber=" + seatNumber + // String concatenation: Adds seatNumber field
                ", row=" + row + // String concatenation: Adds row field
                ", column=" + column + // String concatenation: Adds column field
                ", qrCode='" + qrCode + '\'' + // String concatenation: Adds qrCode field with quotes
                ", createdAt=" + createdAt + // String concatenation: Adds createdAt timestamp
                ", updatedAt=" + updatedAt + // String concatenation: Adds updatedAt timestamp
                '}'; // String concatenation: Closes the string representation
    }
} // Class closing brace: End of SeatingAssignment class
