package com.examseating.model; // Package declaration: Defines the package this class belongs to (com.examseating.model)

import javax.persistence.*; // Import statement: Imports all JPA annotations for database mapping (@Entity, @Table, @Id, @Column, etc.)
import javax.validation.constraints.*; // Import statement: Imports all validation constraints (@NotBlank, @Size, @Email, @Pattern, @Min, @Max)
import java.time.LocalDateTime; // Import statement: Imports LocalDateTime class for timestamp fields
import java.util.List; // Import statement: Imports List interface for collections

/**
 * Student entity representing a student in the system
 */
@Entity // JPA annotation: Marks this class as a database entity (table mapping)
@Table(name = "students") // JPA annotation: Specifies the database table name as 'students'
public class Student { // Class declaration: Public class named Student representing a student entity
    
    @Id // JPA annotation: Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // JPA annotation: Specifies auto-increment strategy for primary key generation
    private Long id; // Field declaration: Primary key field (auto-generated by database)
    
    @NotBlank(message = "Student ID is required") // Validation annotation: Ensures field is not blank, with custom error message
    @Column(unique = true, nullable = false) // JPA annotation: Makes column unique and not nullable in database
    private String studentId; // Field declaration: Unique student identifier string
    
    @NotBlank(message = "Name is required") // Validation annotation: Ensures field is not blank
    @Size(max = 100, message = "Name must not exceed 100 characters") // Validation annotation: Limits string length to 100 characters
    private String name; // Field declaration: Student's full name
    
    @NotBlank(message = "Roll number is required") // Validation annotation: Ensures field is not blank
    @Column(unique = true, nullable = false) // JPA annotation: Makes column unique and not nullable
    private String rollNumber; // Field declaration: Unique roll number assigned to student
    
    @NotBlank(message = "Class is required") // Validation annotation: Ensures field is not blank
    private String className; // Field declaration: Class or grade the student belongs to
    
    @NotBlank(message = "Section is required") // Validation annotation: Ensures field is not blank
    private String section; // Field declaration: Section within the class
    
    @NotBlank(message = "Exam subject is required") // Validation annotation: Ensures field is not blank
    private String examSubject; // Field declaration: Subject the student is taking exam for (used for anti-cheating algorithm)
    
    @Email(message = "Invalid email format") // Validation annotation: Validates email format
    private String email; // Field declaration: Student's email address
    
    @Pattern(regexp = "^\\+?[1-9]\\d{1,14}$", message = "Invalid phone number format") // Validation annotation: Validates phone number format with regex
    private String phone; // Field declaration: Student's phone number
    
    @ElementCollection // JPA annotation: Marks this field as a collection of basic types stored in separate table
    @CollectionTable(name = "student_special_requirements", joinColumns = @JoinColumn(name = "student_id")) // JPA annotation: Specifies join table name and foreign key column
    @Column(name = "requirement") // JPA annotation: Specifies column name in the join table
    private List<String> specialRequirements; // Field declaration: List of special requirements (e.g., wheelchair access, extra time)
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable in database
    private Boolean isActive = true; // Field declaration: Soft delete flag (true = active, false = deleted)
    
    @Column(nullable = false, updatable = false) // JPA annotation: Makes column not nullable and not updatable
    private LocalDateTime createdAt; // Field declaration: Timestamp when student record was created
    
    @Column(nullable = false) // JPA annotation: Makes column not nullable
    private LocalDateTime updatedAt; // Field declaration: Timestamp when student record was last updated
    
    // Constructors
    public Student() { // Constructor declaration: No-argument constructor (default)
        this.createdAt = LocalDateTime.now(); // Assignment: Sets createdAt to current timestamp
        this.updatedAt = LocalDateTime.now(); // Assignment: Sets updatedAt to current timestamp
    }
    
    public Student(String studentId, String name, String rollNumber, String className, String section) { // Constructor declaration: Parameterized constructor with basic student info
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.studentId = studentId; // Assignment: Sets studentId field
        this.name = name; // Assignment: Sets name field
        this.rollNumber = rollNumber; // Assignment: Sets rollNumber field
        this.className = className; // Assignment: Sets className field
        this.section = section; // Assignment: Sets section field
        this.examSubject = "Mathematics"; // Assignment: Sets default exam subject to Mathematics
    }
    
    public Student(String studentId, String name, String rollNumber, String className, String section, String examSubject) { // Constructor declaration: Parameterized constructor with exam subject
        this(); // Constructor chaining: Calls no-argument constructor to set timestamps
        this.studentId = studentId; // Assignment: Sets studentId field
        this.name = name; // Assignment: Sets name field
        this.rollNumber = rollNumber; // Assignment: Sets rollNumber field
        this.className = className; // Assignment: Sets className field
        this.section = section; // Assignment: Sets section field
        this.examSubject = examSubject; // Assignment: Sets examSubject field
    }
    
    // Getters and Setters
    public Long getId() { // Getter method: Returns the id field value
        return id; // Return statement: Returns the primary key id
    }
    
    public void setId(Long id) { // Setter method: Sets the id field value
        this.id = id; // Assignment: Sets the primary key id
    }
    
    public String getStudentId() { // Getter method: Returns the studentId field value
        return studentId; // Return statement: Returns the student ID string
    }
    
    public void setStudentId(String studentId) { // Setter method: Sets the studentId field value
        this.studentId = studentId; // Assignment: Sets the student ID
    }
    
    public String getName() { // Getter method: Returns the name field value
        return name; // Return statement: Returns the student name
    }
    
    public void setName(String name) { // Setter method: Sets the name field value
        this.name = name; // Assignment: Sets the student name
    }
    
    public String getRollNumber() { // Getter method: Returns the rollNumber field value
        return rollNumber; // Return statement: Returns the roll number
    }
    
    public void setRollNumber(String rollNumber) { // Setter method: Sets the rollNumber field value
        this.rollNumber = rollNumber; // Assignment: Sets the roll number
    }
    
    public String getClassName() { // Getter method: Returns the className field value
        return className; // Return statement: Returns the class name
    }
    
    public void setClassName(String className) { // Setter method: Sets the className field value
        this.className = className; // Assignment: Sets the class name
    }
    
    public String getSection() { // Getter method: Returns the section field value
        return section; // Return statement: Returns the section
    }
    
    public void setSection(String section) { // Setter method: Sets the section field value
        this.section = section; // Assignment: Sets the section
    }
    
    public String getExamSubject() { // Getter method: Returns the examSubject field value
        return examSubject; // Return statement: Returns the exam subject
    }
    
    public void setExamSubject(String examSubject) { // Setter method: Sets the examSubject field value
        this.examSubject = examSubject; // Assignment: Sets the exam subject
    }
    
    public String getEmail() { // Getter method: Returns the email field value
        return email; // Return statement: Returns the email address
    }
    
    public void setEmail(String email) { // Setter method: Sets the email field value
        this.email = email; // Assignment: Sets the email address
    }
    
    public String getPhone() { // Getter method: Returns the phone field value
        return phone; // Return statement: Returns the phone number
    }
    
    public void setPhone(String phone) { // Setter method: Sets the phone field value
        this.phone = phone; // Assignment: Sets the phone number
    }
    
    public List<String> getSpecialRequirements() { // Getter method: Returns the specialRequirements field value
        return specialRequirements; // Return statement: Returns the list of special requirements
    }
    
    public void setSpecialRequirements(List<String> specialRequirements) { // Setter method: Sets the specialRequirements field value
        this.specialRequirements = specialRequirements; // Assignment: Sets the list of special requirements
    }
    
    public Boolean getIsActive() { // Getter method: Returns the isActive field value
        return isActive; // Return statement: Returns the active status flag
    }
    
    public void setIsActive(Boolean isActive) { // Setter method: Sets the isActive field value
        this.isActive = isActive; // Assignment: Sets the active status flag
    }
    
    public LocalDateTime getCreatedAt() { // Getter method: Returns the createdAt field value
        return createdAt; // Return statement: Returns the creation timestamp
    }
    
    public void setCreatedAt(LocalDateTime createdAt) { // Setter method: Sets the createdAt field value
        this.createdAt = createdAt; // Assignment: Sets the creation timestamp
    }
    
    public LocalDateTime getUpdatedAt() { // Getter method: Returns the updatedAt field value
        return updatedAt; // Return statement: Returns the last update timestamp
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) { // Setter method: Sets the updatedAt field value
        this.updatedAt = updatedAt; // Assignment: Sets the last update timestamp
    }
    
    @PreUpdate // JPA annotation: Marks this method to run before entity update operation
    public void preUpdate() { // Method declaration: Lifecycle callback method that runs before update
        this.updatedAt = LocalDateTime.now(); // Assignment: Updates the updatedAt timestamp to current time
    }
    
    @Override // Annotation: Indicates this method overrides the Object class toString() method
    public String toString() { // Method declaration: Overrides toString() to provide string representation of object
        return "Student{" + // String concatenation: Starts building string representation
                "id=" + id + // String concatenation: Adds id field
                ", studentId='" + studentId + '\'' + // String concatenation: Adds studentId field with quotes
                ", name='" + name + '\'' + // String concatenation: Adds name field with quotes
                ", rollNumber='" + rollNumber + '\'' + // String concatenation: Adds rollNumber field with quotes
                ", className='" + className + '\'' + // String concatenation: Adds className field with quotes
                ", section='" + section + '\'' + // String concatenation: Adds section field with quotes
                ", email='" + email + '\'' + // String concatenation: Adds email field with quotes
                ", phone='" + phone + '\'' + // String concatenation: Adds phone field with quotes
                ", specialRequirements=" + specialRequirements + // String concatenation: Adds specialRequirements list
                ", isActive=" + isActive + // String concatenation: Adds isActive flag
                ", createdAt=" + createdAt + // String concatenation: Adds createdAt timestamp
                ", updatedAt=" + updatedAt + // String concatenation: Adds updatedAt timestamp
                '}'; // String concatenation: Closes the string representation
    }
} // Class closing brace: End of Student class
